[package]
name = "freyr-gui"
version = "0.1.0"
authors = ["Miraclx <omiraculous@gmail.com>"]
edition = "2018"
description = "A cross-platform front-end GUI for freyr-js written in Rust"
license = "Apache-2.0"
repository = "https://github.com/miraclx/freyr-gui"

[dependencies]
